version: 2
jobs:
  build:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Install CMake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Emscripten
          command: 'apt-get update && apt-get install -y emscripten'
      - run:
          name: Configure
          command: 'emconfigure cmake ..'
      - run:
          name: Build
          command: 'emmake make'
