version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: /tmp/hexagon
    environment:
    steps:
      - run:
          name: Update
          command: 'apt-get update'
      - run:
          name: Install CMake
          command: 'apt-get install -y cmake'
      - run:
          name: Install Emscripten dependencies
          command: 'apt-get install -y git python2.7-minimal python-minimal'
      - checkout
      - run:
          name: Install and configure Emscripten
          command: |
            git clone https://github.com/juj/emsdk.git
            cd emsdk
            git pull
            ./emsdk install latest
            ./emsdk activate latest
      - run:
          name: Configure & build
          command: |
            git submodule update --init --recursive
            source ./emsdk/emsdk_env.sh
            mkdir build && cd build
            emconfigure
            emconfigure cmake ..
            emmake make
