version: 2
jobs:
  test-model-js:
    docker:
      - image: ubuntu:latest
    working_directory: /tmp/hexagon
    environment:
    steps:
      - run:
          name: Update
          command: 'apt-get update'
      - run:
          name: Install dev dependencies
          command: 'apt-get install -y cmake git python2.7-minimal python-minimal'
      - checkout
      - run:
          name: Install and configure Emscripten
          command: |
            git clone https://github.com/juj/emsdk.git
            cd emsdk
            git pull
            ./emsdk install latest
            ./emsdk activate latest
      - run:
          name: Configure, build & test
          command: |
            git submodule update --init --recursive
            source ./emsdk/emsdk_env.sh
            mkdir build && cd build
            emconfigure cmake ..
            emmake make -j4 model-test
            ctest -j4

  test-model-binary:
    docker:
      - image: ubuntu:latest
    working_directory: /tmp/hexagon
    environment:
    steps:
      - run:
          name: Update
          command: 'apt-get update'
      - run:
          name: Install dev dependencies
          command: 'apt-get install -y cmake git build-essential'
      - checkout
      - run:
          name: Configure, build & test
          command: |
            git submodule update --init --recursive
            mkdir build && cd build
            cmake ..
            make -j4 model-test
            ctest -j4

  build-client:
    docker:
      - image: ubuntu:latest
    working_directory: /tmp/hexagon
    environment:
    steps:
      - run:
          name: Update
          command: 'apt-get update'
      - run:
          name: Install dev dependencies
          command: 'apt-get install -y cmake git python2.7-minimal python-minimal'
      - checkout
      - run:
          name: Install and configure Emscripten
          command: |
            git clone https://github.com/juj/emsdk.git
            cd emsdk
            git pull
            ./emsdk install latest
            ./emsdk activate latest
      - run:
          name: Configure, build & test
          command: |
            git submodule update --init --recursive
            source ./emsdk/emsdk_env.sh
            mkdir build && cd build
            emconfigure cmake ..
            emmake make -j4
            cpack -G 7Z
            mkdir /tmp/hexagon/release
            mv *.7z -t /tmp/hexagon/release
            cp ../VERSION /tmp/hexagon/release
            chmod -R o+rw /tmp/hexagon

      - persist_to_workspace:
          root: /tmp/hexagon
          paths:
            - ./release

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    working_directory: /tmp/hexagon
    steps:
      - attach_workspace:
          at: /tmp/hexagon
      - run:
          name: Publish Release on GitHub
          command: |
            TAG="$(cat release/VERSION)"
            rm /tmp/hexagon/release/VERSION
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete "$TAG" /tmp/hexagon/release

workflows:
  version: 2
  integration:
    jobs:
      - test-model-binary
      - test-model-js
      - build-client:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build-client
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

